name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black=22.12.0
  - bokeh
  - cudatoolkit=11.3.1
  - cudnn=8.4.1.50
  - easydict
  - flake8
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - pip
  - pillow
  - pre-commit
  - pydantic
  - pylint
  - pytorch=1.12.1
  - scikit-image
  - scikit-learn
  - streamlit
  - torchmetrics=0.11.0
  - torchvision=0.13.1
  - vim
  - wandb
  - pip:
    - mediapipe==0.9.0.1
    - pytorch-lightning[extra]
    - pytorch-mtcnn
