name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cudatoolkit`
  - cudnn
  - easydict
  - flake8
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - pytorch-lightning=1.8.1
  - pip
  - pillow
  - pre-commit
  - pydantic
  - pylint
  - pytorch=1.13.1
  - scikit-image
  - streamlit
  - torchmetrics
  - torchvision
  - vim
  - wandb
  - pip:
    - mediapipe=0.9.0.1
