name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cudatoolkit=11.3.1
  - cudnn
  - dvc
  - easydict
  - flake8
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - pip
  - pillow
  - pre-commit
  - pydantic
  - pylint
  - pytorch=1.12.1
  - scikit-image
  - streamlit
  - torchmetrics
  - torchvision
  - vim
  - wandb
  - pip:
    - mediapipe==0.9.0.1
    - pytorch-lightning[extra]
