name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - bokeh
  - cudatoolkit=11.7
  - cudnn=8.2.1
  - easydict
  - flake8
  - isort
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - pip
  - pillow
  - pre-commit
  - pydantic
  - pylint
  - pytorch=1.13.1
  - scikit-image
  - streamlit
  - torchvision
  - vim
  - pip:
    - mediapipe=0.9.0.1
