# pytorch_lightning==1.9.0
seed_everything: 40
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: cifar
  enable_checkpointing: true
  accelerator: gpu
  max_epochs: 300
  precision: 32
  strategy:
    class_path: pytorch_lightning.strategies.DDPSpawnStrategy
    init_args:
      find_unused_parameters: false
model:
  inpput_shape:
  - 3
  - 224
  - 224
  num_target_classes: 10000
  learning_rate: 0.0003
data:
  data_dir: data/digiface1m/aligned/
  # data_dir: data/cifar5/
  image_size: 224
  batch_size: 512
