# pytorch_lightning==1.9.0
seed_everything: 40
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: facerec
      log_model: "all"
  enable_checkpointing: true
  accelerator: gpu
  max_epochs: 30
  precision: 32
  # strategy:
  #   class_path: pytorch_lightning.strategies.DDPSpawnStrategy
  #   init_args:
  #     find_unused_parameters: false
model:
  inpput_shape:
  - 3
  - 112
  - 112
  # num_target_classes: 93431
  num_target_classes: 10000
  learning_rate: 0.0003
  classifier_type: "arcproduct"
  margin_penalty: 8.0
  margin_scale: 0.01
data:
  data_dir: data/digiface1m/aligned/
  # data_dir: data/ms1m-retinaface-t1/
  # data_dir: data/cifar5/
  image_size: 112
  batch_size: 1536
